### ISSUE TITLE
Maureen's To-Do

### ISSUE THREAD

**Issue by meticulaedesigns** [MT-Group-Projects/automaton#1]
## figure out how github projects works
- [x] find some good instruction videos
- [x] play with settings
- [x] create some action items (issues?)
- [x] figure out if making this an organization gives us roles
- [x] can I add pictures to issues?
- [x] stl files?

## questions I need help with
- [ ] use project associated with repository or org?
- [ ] rename/recreate this repository (unchangable name could cause problems down the road - could be more than one automaton for MTGP)
- [ ] separate repository for cad vs pm? or separate project? or all in one?
- [ ] separate repo for each system/variant?
- [x] separate private project for credits?
- [ ] automations: when issue labeled CAD Team is closed, change project status, API send message to discord channel, 
- [x] save out project table as csv?
- [x] what roles/can everyone change project data to right of issue (and at repo/project/org level?)
- [x] can anyone reopen or just those who closed or created or is it a role
- [ ] what is the difference between managing people at repo, project, or org level (where do I add them/do I have to add people multiple times?)
- [x] which labels do which automatic things in projects
- [x] wiki sidebar sort https://stackoverflow.com/questions/39396362/github-wiki-pages-sort-order

## pm todo
- [ ] read cad standards
- [ ] look at mmx fusion file structure & naming
- [ ] read andy's report & find all pics
- [ ] read fitfd book
- [ ] gather list of vids

**Comment by meticulaedesigns** [comment]
Testing closing this issue...
